version: '3'
services:
  dbt_example:
    environment:
    - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    working_dir: /workspace
    volumes:
    - type: bind
      source: ${HOME}/.gitconfig
      target: /home/vscode/.gitconfig
    - type: bind
      source: "/run/host-services/ssh-auth.sock"
      target: "/run/host-services/ssh-auth.sock"
    - type: bind
      source: ${HOME}/.gnupg
      target: /home/vscode/.gnupg
    - type: bind
      source: ${HOME}/.ssh
      target: /home/vscode/.ssh
